- name: Assorted software
  hosts: localhost
  tasks:
    - name: Install apt software
      become: true
      apt:
        name:
          - curl
          - git
          - hunspell-es # Spanish dictionary
          - shellcheck
          - vim
          - wl-clipboard # Shellcheck
        update_cache: yes
        state: present
    - name: Install sandboxed snap applications
      community.general.snap:
        name:
          - snap-store
          - spotify
          - todoist
          - vlc
    - name: Install non sandboxed snap software
      community.general.snap:
        name:
          - code
        classic: false
    - name: Install flatpak applications
      community.general.flatpak:
        state: present
        method: user
        name:
          - app.devsuite.Ptyxis
          - com.discordapp.Discord
          - com.brave.Browser
          - com.github.finefindus.eyedropper
          - com.github.PintaProject.Pinta
          - com.github.tchx84.Flatseal
          - io.missioncenter.MissionCenter
          - org.gimp.GIMP
          - org.gnome.Boxes
          - org.gtk.Gtk3theme.Yaru-Blue-dark/x86_64/3.22 # The default Yaru version installed is 3.22
          - org.libreoffice.LibreOffice
          - org.mozilla.Thunderbird
    - name: Install orphan debs
      block:
        # NAPS2 it's also offered as a Flatpak but given the USB limitations with Flatpak
        # that version is literally useless for me.
        - name: naps2
          block:
            - import_tasks: lib/install-orphan-deb.yaml
              vars:
                naps2_version: 8.2.1
                deb_url: https://github.com/cyanfish/naps2/releases/download/v{{ naps2_version }}/naps2-{{ naps2_version }}-linux-x64.deb
                # Install NAPS2, sha256sum calculated Sep 01st, 2025
                deb_hash: sha256:8e23c4a6d7f0b75512459cc29a639ec395355f222375291ed674525c7c9cd4b7
        - name: Simplenote
          block:
            - import_tasks: lib/install-orphan-deb.yaml
              vars:
                simplenote_version: 2.23.2
                deb_url: https://github.com/Automattic/simplenote-electron/releases/download/v{{ simplenote_version }}/Simplenote-linux-{{ simplenote_version }}-amd64.deb
                # Install Simplenote, sha256sum calculated Jun 02nd, 2025
                deb_hash: sha256:ae5c5a46347d68031324633c27f33afdeabfc6ffca5f58dd638002e6db99f22b
        - name: Steam
          block:
            - import_tasks: lib/install-orphan-deb.yaml
              vars:
                steam_version: 1.0.0.81
                deb_url: https://repo.steampowered.com/steam/archive/stable/steam-launcher_{{ steam_version }}_all.deb
                # Install Simplenote, sha256sum calculated Jun 02nd, 2025
                deb_hash: sha256:afd2b922f9771a9ca7ee0cb416bdd4fceabf3e75a2c5b65f654a10419762960d
