- name: Install scripting runtimes
  hosts: localhost
  tasks:
    - name: nvm
      block:
        - import_tasks: lib/install-from-github.yaml
          vars:
            repository: nvm-sh/nvm
            ref: v0.39.5
            installer: install.sh
            checksum_algorithm: sha256
            # sha256sum calculated Sept 23th, 2023
            checksum: 69da4f89f430cd5d6e591c2ccfa2e9e3ad55564ba60f651f00da85e04010c640
    - name: rbenv
      block:
        - import_tasks: lib/install-from-github.yaml
          vars:
            repository: rbenv/rbenv-installer
            ref: 33926644327c067be973c8e1c6c4f5c2178d4ead
            installer: bin/rbenv-installer
            checksum_algorithm: sha256
            # sha256sum calculated Sept 23th, 2023
            checksum: e5fe1edc05d827bc87f7ea9724b19632cc68bff10a04912bfd1017385f22f2fb
